### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by stmlange** [haproxytech/haproxy-docker-alpine#10]
Hello, thanks for this great docker image! Is there a place for a changelog? In particular know what has changed between versions without creating a git diff?

Similar to https://github.com/prometheus/prometheus/releases or any other "changelog" / "release history". 
Thanks!

**Comment by dkorunic** [comment]
@stmlange We typically do have larger Changelogs, but this is a more-less fully automated build system that builds a new Docker image upon new HAProxy release. If you want to see HAProxy Changelogs, they are here, separately for each branch: https://www.haproxy.org/
Docker images in general don't have much changes so that having a detailed Changelog would make sense.

**Comment by stmlange** [comment]
Thanks
