### ISSUE TITLE
Automatic Builds still failing for 2.9.2

### ISSUE THREAD

**Issue by cmason3** [haproxytech/haproxy-docker-alpine#12]
Sorry, but it is still failing..

![image](https://github.com/haproxytech/haproxy-docker-alpine/assets/57402469/6f60b5d1-addc-4574-882d-4c80fd5f4df9)

**Comment by dkorunic** [comment]
Sadly Golang Docker images have dropped multiple architectures in their default image. I've resolved this by going for Golang Alpine variant of Docker image in https://github.com/haproxytech/haproxy-docker-alpine/commit/1207ddf74ee15b01dfbd98006d8e01be9fed4644 and https://github.com/haproxytech/haproxy-docker-alpine/commit/920253468837aa068c66a3c9e5611ff2626beaaf. Builds have completed since.
