### ISSUE TITLE
Errors since forced Dataplane API upgrade

### ISSUE THREAD

**Issue by arouxAgicap** [haproxytech/haproxy-docker-alpine#13]
Since your latest [Automated commit](https://github.com/haproxytech/haproxy-docker-alpine/commit/8261f990d43ddf1a5ff920719079d25684fb820f) all our haproxy instance started to fail. 
When we looked at our images we saw that the dataplane API version was bumped to the latest and breaking version. We wanted to rollback on previous image and we saw that all your images was updated with this version.

We mainly use the dataplane API to sync our peers for rate-limiting purpose.

It forces us to rebuild in emergency an image for our production environment like you can see in the [post](https://x.com/sreguys/status/1833620173372145993)

Is there a way to prevent this incident or at least to be aware of such a change ?

**Comment by dkorunic** [comment]
@arouxAgicap We are generally trying **very hard** to avoid breaking changes for our users and customers. However, in this particular scenario we have two different semvers, one being HAProxy CE and another being Dataplaneapi and both of these products is developed by different team and follows different somewhat development cycles. It has been decided that the HAProxy CE Docker images will be tagged primarily with the semver of the major (HAProxy CE) product as the double-tagging the image (ie. `haproxy-alpine:3.0.4-3.0.0`) would be too confusing for everyone, it would also cause us to have multiple copies of the product with security issues since Golang runtime has frequent security issues. We often rebuild/release newer Dataplaneapi releases and with per-Dataplaneapi tagging we'd have still reachable tags/layers/images with known CVEs.

While we understand this is not the best solution for everyone, we have considered alternatives and haven't found something that would work better in most cases.

**Comment by arouxAgicap** [comment]
Thank you for your response @dkorunic. We saw the blog article announcing the new major release of the dataplane API but we did not expect that all the images would be updated with the last version of the dataplane API.

If all the 3.X.X images would have been updated with the version 3.0.0 of the dataplane API and the 2.X.X were left in with the last 2.X.X version of the dataplane API it would have allow us to rollback easily.

**Comment by dkorunic** [comment]
@arouxAgicap We've working on bringing both latest v2 and v3 dataplaneapi binaries in HAProxy CE images, right now, as quick as possible. I'll let you know as soon as that's been completed and new images been pushed to build pipeline.

**Comment by imiric** [comment]
Just to chime in that our team was also affected by this.

It's surprising that the `2.8.10` image has HAProxy v2.8.10 but Data Plane API v3.0.0:

```
/ # haproxy --version 2>/dev/null | head -1
HAProxy version 2.8.10-f28885f 2024/06/14 - https://haproxy.org/
/ # dataplaneapi --version 2>/dev/null | head -1
HAProxy Data Plane API v3.0.0 1491b08a
```

Shipping v3 of the Data Plane API in the 2.x image was the problem for us. If at least the major versions were consistent that would've avoided it. But we were able to work around it by pinning the image to `2.8.9` instead, so it's not a major problem.

**Comment by dkorunic** [comment]
Understood. We are deeply sorry that so many users are affected by this and as I said, we'll have new images with both binaries: `/usr/local/bin/dataplaneapi` being latest v3 release and `/usr/local/bin/dataplaneapi-v2` being latest v2 release, so users will be able to seamlessly switch when needed.

**Comment by dkorunic** [comment]
Just to ping you back, HAProxy CE Alpine images are being built as we speak (you can monitor the [progress](https://github.com/haproxytech/haproxy-docker-alpine/actions)) and they contain both binaries as noted above. Build pipeline has almost finished building all images.

**Comment by dkorunic** [comment]
Image builds have been completed and I'll close the issue -- of course I am going to do the same change to Debian and Ubuntu images next, don't worry.
