### ISSUE TITLE
Haproxy Response Header

### ISSUE THREAD

**Issue by matheuscaselani** [haproxytech/haproxy-docker-alpine#3]
I'm currently running Haproxy 2.2.5 and using this following API path : /v2/services/haproxy/configuration/defaults to get the header "Configuration-Version" from haproxy.cfg head file, but im having a memory leak problem with dataplane api.

After upgrading to any of the latest versions available ( 2.5, or even 2.4 ), the response header "configuration-version" no longer works. Does anybody know what happened or if i have to enable it somewhere ?

**Comment by dkorunic** [comment]
@matheuscaselani I am seeing that you have already pinged on a corresponding issue in Dataplaneapi project (https://github.com/haproxytech/dataplaneapi/issues/239) so there is no need to have this open here, since this project is related to updating and packaging HAProxy for Docker, which does include Dataplane API, but developers won't see the ticket here.
